[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mycalcdaap = "Dzzsa8C76RCT4TDra3UvB8HnsPrLh7tBhUwAHnY9XEou"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/vinayputta/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[tests]
test.startup_wait = 15

